# Generated by Django 4.0.5 on 2022-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0004_alter_response_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='email',
            field=models.EmailField(blank=True, default='tall@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
