# Generated by Django 3.2.12 on 2022-03-12 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('scaleQuestion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NpsScaleSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scaleSettingName', models.CharField(max_length=255)),
                ('settingID', models.CharField(max_length=200)),
                ('eventID', models.CharField(max_length=200)),
                ('productCategory', models.CharField(max_length=255)),
                ('productSubCategory', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('help_YT', models.URLField(null=True)),
                ('orientation', models.CharField(max_length=255)),
                ('bg_color', models.CharField(max_length=255)),
                ('scale_color', models.CharField(max_length=255)),
                ('font_color', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'NPS Scale Settings',
            },
        ),
        migrations.CreateModel(
            name='NpsScaleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('npsscore', models.CharField(max_length=100)),
                ('npsoutput', models.CharField(max_length=100)),
                ('responseTime', models.CharField(max_length=24)),
                ('settingID', models.CharField(max_length=200)),
                ('eventID', models.CharField(max_length=200)),
                ('sessionID', models.CharField(max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='npsScale.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'NPS Scale',
            },
        ),
        migrations.CreateModel(
            name='nps_scores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='10', max_length=50)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='npsScale.product')),
            ],
        ),
    ]
