# Generated by Django 3.2.12 on 2022-03-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npsScale', '0002_auto_20220313_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nps_scores',
            name='timer',
        ),
    ]
