# Generated by Django 4.0.5 on 2022-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='system_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('orientation', models.CharField(choices=[('horizontal', 'horizontal'), ('vertical', 'vertical')], max_length=10)),
                ('numberrating', models.IntegerField()),
                ('scalecolor', models.CharField(max_length=20)),
                ('roundcolor', models.CharField(max_length=20)),
                ('fontcolor', models.CharField(max_length=20)),
                ('fomat', models.CharField(max_length=500)),
                ('left', models.CharField(max_length=50)),
                ('right', models.CharField(max_length=50)),
                ('center', models.CharField(blank=True, max_length=50)),
                ('time', models.IntegerField(blank=True)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('template_name', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
    ]
