# Generated by Django 4.0.5 on 2022-07-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='category',
        ),
        migrations.AddField(
            model_name='response',
            name='brand_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='response',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='response',
            name='scale_name',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterModelTable(
            name='system_settings',
            table=None,
        ),
    ]
