name: Build & Deploy

on:
  push:
    branches: [frontend-production]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      # - run: npm install -g npm
      - run: npm ci
      - run: CI=false vite build
      - uses: actions/upload-artifact@v2
        with:
          name: production
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/frontend-production'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: production
          path: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
